# Reference NixOS configuration for Niri + iNiR.
#
# This is a WORKING EXAMPLE, not a drop-in file — copy the pieces you need
# into your own /etc/nixos/configuration.nix, and change the values marked
# "CHANGE ME" below to match your machine.

{ config, pkgs, inir, ... }:

{
  imports = [
    inir.nixosModules.inir
    ./hardware-configuration.nix     # CHANGE ME: use YOUR own, generated by `nixos-generate-config`
  ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = "nixos";     # CHANGE ME
  networking.networkmanager.enable = true;

  time.timeZone = "America/Mexico_City";   # CHANGE ME
  i18n.defaultLocale = "es_MX.UTF-8";      # CHANGE ME

  programs.dconf.enable = true;      # needed for GTK app settings (file picker, etc.) to persist

  # Fixes scripts inside iNiR that call /bin/cat directly (FHS assumption).
  # NixOS has no /bin/cat by default; iNiR's battery/threshold scripts break
  # without this symlink.
  systemd.tmpfiles.rules = [
    "L+ /bin/cat - - - - ${pkgs.coreutils}/bin/cat"
  ];

  users.users."ltar" = {             # CHANGE ME: your own username
    isNormalUser = true;
    description = "LTAR";
    extraGroups = [ "networkmanager" "wheel" ];
  };

  # extraPackages (below, in `programs.inir`) only wires Qt plugin/QML search
  # paths — it does NOT add executables to inir.service's own $PATH (that
  # PATH is a short fixed list). Scripts the shell spawns internally
  # (python3, jq, cliphist, ddcutil, etc.) need to be listed here instead,
  # or they silently fail with "Process failed to start" in `inir logs`.
  systemd.user.services.inir.path = with pkgs; [
    (python3.withPackages (ps: with ps; [ pip materialyoucolor pillow evdev numpy ]))
    jq
    cliphist
    ddcutil
  ];

  programs.inir = {
    enable = true;
    service.compositor = "niri";
    extraPackages = import ./modules/inir-deps.nix { inherit pkgs; };
  };

  # Optional but recommended: a login manager. Any Wayland-capable DM works;
  # GDM is what's tested here.
  services.xserver.enable = true;
  services.displayManager.gdm.enable = true;

  programs.niri.enable = true;
  system.stateVersion = "26.05";     # CHANGE ME: keep at the version of your FIRST install
}
